name: Build & Test Main

on:
  push:
    tags: [ release-* ]

env:
    NETCORE_VERSION: '5.0.x'
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    PROJECT_NAME: Typeahead
    GITHUB_FEED: https://nuget.pkg.github.com/timbze/index.json

jobs:
  build:
    name: Build, test and pack
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore src/Blazored.$PROJECT_NAME/Blazored.$PROJECT_NAME.csproj

    - name: Test
      run: dotnet test -c Release

    - name: Create Nuget Package
      run: |
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        echo Version: $VERSION
        VERSION="${VERSION//release-}"
        echo Clean Version: $VERSION
        dotnet pack -v normal -c Release --no-restore --include-symbols --include-source -p:PackageVersion=$VERSION-timbze src/Blazored.$PROJECT_NAME/Blazored.$PROJECT_NAME.*proj
        for f in ./src/Blazored.${{ env.PROJECT_NAME }}/bin/Release/*.nupkg
        do
          dotnet nuget push $f --source $GITHUB_FEED --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        done
